### ISSUE TITLE
uniffi-dl no longer compatible with latest version of IntelliJ

### ISSUE THREAD

**Issue by jeddai** [Lonami/uniffi-dl#3]
I recently upgraded to IntelliJ IDEA version 2023.1 (Build #IU-231.8109.175) and my plugins pane is reporting that the uniffi-dl plugin requires version 223.* or earlier.

Not sure what needs to be done to support the new version of IntelliJ. I'm happy to contribute this just trying to figure out how all this works atm.

**Comment by Lonami** [comment]
Thanks for the report! Might be enough to bump this number 🤷‍♀️:

https://github.com/Lonami/uniffi-dl/blob/844ff35c7be7bb6508b0f625efeaaf729a5a021a/build.gradle.kts#L31

So if you want to make the change, build to see if it works and send a PR, that'd be great!

**Comment by julioromano** [comment]
@Lonami Will you be so kind to push a new release to the plug-in marketplace?

**Comment by julioromano** [comment]
It seems something went wrong while uploading to the marketplace: https://plugins.jetbrains.com/plugin/20527-uniffi-dl/versions

The supported version range is the same as of the previous version :(

**Comment by Lonami** [comment]
I can see it just fine:
![image](https://github.com/Lonami/uniffi-dl/assets/6297805/f918f835-3649-429d-b9b4-be11095f27f7)

And Friday got this email:

> Hello Lonami E,
> 
> Version 0.3.0 of the Uniffi-DL plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/20527-uniffi-dl/versions/stable/341532.
> 
> If you have any questions or comments, feel free to send them our way by replying to this email. Please keep the same email subject.
> 
> Thank you for developing plugins for JetBrains products!
> 
> Best regards,
> The JetBrains Marketplace team

Maybe we can give it a few more days and if it still doesn't show up I can respond to them.

**Comment by julioromano** [comment]
I see it too, but `compatibility range` is wrong. It is the same as for 0.2.2. 
But instead it should be 223.*-231.*

**Comment by Lonami** [comment]
So you're telling me I forgot to pull these changes before bumping it to v0.3! I would never… oh. I'll fix that later today.

**Comment by Lonami** [comment]
Now it should be up for reals, sorry for the noise.

**Comment by julioromano** [comment]
Works like a charm! Thanks a lot!
