### ISSUE TITLE
Incompatibility with the latest Idea versions

### ISSUE THREAD

**Issue by a2xchip** [Lonami/uniffi-dl#7]
Hi, there is compatibility issue with the latest Idea IDEs. 

Update would be appreciated. If no time right now - I'm ready to contribute. 

<img width="574" alt="Screenshot 2024-03-28 at 19 39 41" src="https://github.com/Lonami/uniffi-dl/assets/6627334/c43ffe30-6809-41d6-9bd4-f4d2aec2629b">

**Comment by Lonami** [comment]
I'll be honest I'm trying to upgrade it but I have no idea what values to use.

If you send a pull request like #5 I can publish a new release at some point.

**Comment by ovitrif** [comment]
Would most likely pick this up today and target to submit a PR

**Comment by ovitrif** [comment]
@Lonami please check my PR: #8 
A week later, I finally found the time today for this 🙏🏻

**Comment by ovitrif** [comment]
> I'll be honest I'm trying to upgrade it but I have no idea what values to use.

If you're using JetBrains Toolbox to install the IDEs, there's an easy way to know which values to use for IDE & build version:

1. enable this option in `JetBrains Toolbox` > `Settings` 
   <img width="400" src="https://github.com/user-attachments/assets/6cac4c4e-4ac9-4b16-8d2f-c12a00295c37">

2. Go back to main screen of `JetBrains Toolbox` and check the build number
   <img width="400" src="https://github.com/user-attachments/assets/cbe1eef6-1ce2-4081-ad7f-e1d45bd51a20">

**Comment by Lonami** [comment]
![image](https://github.com/user-attachments/assets/0ad1a070-05f2-4089-9e64-6e5bc491c70b)

Hope I did everything alright. If not please bump the thread again and I'll take another look.
